### ISSUE TITLE
Methods in documentation are depracated

### ISSUE THREAD

**Issue by NA-Dev** [ulfaslak/infostop#13]
Am I correct that the methods in the documentation like infostop.detect.label_trace are depracated? I installed the package, and seem to be only able to use model.fit_predict(data) and plotmap(model).

**Comment by ulfaslak** [comment]
This is correct. I have not had time to update the docs :(. The best reference right now is the README on Github.

**Comment by ulfaslak** [comment]
That said, if you have a look at the code as it is, you'll find that it's pretty well documented. It should not be too hard to figure out how to make full use of Infostop just from looking through the code since it's not a huge library.
