### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by neumannoskar** [ulfaslak/infostop#20]
I'm trying to install Infostop using Python 3.10.4 and Visual Studio 2019. I've tried various proposed fixes listed in the following:

https://stackoverflow.com/questions/50494411/error-command-c-visual-studio-2017-community-vc-tools-msvc-14-14-2642

https://stackoverflow.com/questions/68913607/c-pr

Please find attached the error output during attempted infostop installation and the configurations of Visual Studio.

[infostop_error_output.txt](https://github.com/ulfaslak/infostop/files/8926516/infostop_error_output.txt)
[visual studio config.txt](https://github.com/ulfaslak/infostop/files/8926526/visual.studio.config.txt)

 I am very grateful for any hints.

**Comment by ulfaslak** [comment]
@neumannoskar Did you solve your problem? If so, how?
