### ISSUE TITLE
Typo in main.cpp

### ISSUE THREAD

**Issue by lalessan** [ulfaslak/infostop#8]
Hey Ulf, 
there is a typo in main.cpp.

dtime = coords(i-1, 2) - coords(i, 2);

should be 

dtime = coords(i, 2) - coords(i-1, 2);

Let me know if you want me to fix it or you will do it. 

Cheers!

**Comment by ulfaslak** [comment]
Whoah, that looks like more than a typo. Have you verified that is causes weird behavior? I feel like I have to test this before changing it.

**Comment by ulfaslak** [comment]
OK, I looked again, of course this will only cause the `max_staying_time` not to be respected, ever. I'll fix. THANKS FOR NOTICING!
