### ISSUE TITLE
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

### ISSUE THREAD

**Issue by lcandeago** [ulfaslak/infostop#9]
```
data = np.array([[4.07145000e+01, -7.40028990e+01, 1.58441851e+09],
                  [4.07503000e+01, -7.40014000e+01, 1.58442229e+09]])
model = Infostop(r1=25, r2=25, min_staying_time=300, min_spacial_resolution=1e-5)
labels = model.fit_predict(d)
```

the error comes from here:
```
        self.stat_coords, inverse_indices, self.counts = np.unique(
            self.stat_coords,
            return_inverse=True, return_counts=True, axis=0
        )
```
when stat_coords is empty apparently numpy hits this bug https://github.com/numpy/numpy/issues/15559

Even without the numpy bug, if self.stat_coords is empty the program should just return maybe?

**Comment by ulfaslak** [comment]
Yes, I suppose in this case Infostop should just label both coords -1. Thanks for noting, will fix.

**Comment by ulfaslak** [comment]
Ok I made it so it throws an error that makes a little more sense.
